FROM node:20 AS base



# Production image, copy all the files and run next
FROM base AS runner

RUN DEBIAN_FRONTEND=noninteractive apt-get install  libc6

RUN addgroup --system --gid 1001 nodejs

RUN adduser --system --uid 1001 nextjs

WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED 1

COPY . .

RUN npm install
RUN npm install -g dotenv

RUN npm run build

RUN chown nextjs:nodejs .next

USER nextjs

EXPOSE 3000

ENV PORT 3000
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "start"]